export {default as logo} from "./Topfront Logo1.png"
export {default as flogo} from "./dawdawdaw.png"
export {default as slider1} from "./slider1.jpg"
export {default as slider2} from "./slider2.jpg"
export {default as slider3} from "./slider3.jpg"
export {default as client1} from "./client1.png"
export {default as client2} from "./client2.png"
export {default as client3} from "./client3.png"
export {default as client4} from "./client4.png"
export {default as client5} from "./client5.jpg"
export {default as client6} from "./client6.jpg"
export {default as client7} from "./client7.jpg"
export {default as client8} from "./client8.png"
export {default as client9} from "./client9.png"
export {default as client10} from "./client10.png"
export {default as client11} from "./client11.png"
export {default as client12} from "./client12.png"
export {default as service1} from "./Engineering.jpg"
export {default as service2} from "./industrial.jpg"
export {default as service3} from "./manpower.jpg"
export {default as service4} from "./risk-management-process-definition.webp"
export {default as service5} from "./staffing.jpg"
export {default as service6} from "./Top-6-Software-Development-Methodologies.jpg"
export {default as service7} from "./manpower-management-service.jpg"
 export{default  as service8} from "./industrial_training.jpeg"
export {default as service9} from "./port.jpeg"
export {default as cmd} from "./chairman__1_-removebg-preview.png"
export {default as p1} from "./Picture1.jpg"
export {default as p2} from "./Picture2.jpg"
export {default as p3} from "./Picture3.jpg"
export {default as p4} from "./Picture4.jpg"
export {default as p5} from "./Picture5.jpg"
export {default as clientraj} from "./jatraj.jpg"
export {default as arti} from "./arti.png"
export {default as arti} from "./shree.jpg"


