export {default as aboutgroup} from "./About-The-Group.png"
export {default as team1} from "./cmd-group.jpg"
export {default as team2} from "./nilachal.jpg"
export {default as team3} from "./himanshu.jpg"
export {default as team4} from "./malaya.jpg"
export {default as team5} from "./goutam.jpg"
export {default as team6} from "./Niranjan.jpg"
export {default as team7} from "./TFPL01154 DUSMANTA KUMAR NAYAK.png"
export {default as team8} from "./BB Singh.jpeg"
export {default as team9} from "./Madam.jpg"
export {default as team10} from "./Narayan.jpg"